name: CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
      - "**/*.yaml"
  pull_request:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/*.yaml"

jobs:
  golangci-lint:
    name: Lint AI Proxy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Go test
        run: |
          go test -v -timeout 30s -count=1 ./...

      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --color=always --path-mode=abs

      - name: Run Fix Linter
        uses: golangci/golangci-lint-action@v8
        if: ${{ failure() }}
        with:
          install-mode: none
          args: --fix --color=always --path-mode=abs

      - name: Auto Fix Diff Content
        if: ${{ failure() }}
        run: |
          if git diff --exit-code --color=always; then
            echo "No changes detected after auto-fix"
          else
            git diff --color=always
            exit 1
          fi
